name: CI/CD Pipeline with Spring Boot, Gradle, and Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Dar permisos de ejecución al wrapper de Gradle
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      # Construir el proyecto
      - name: Build with Gradle
        run: ./gradlew clean build

      # Verificar el archivo JAR generado
      - name: Verify JAR file
        run: ls build/libs/

      # Guardar el artefacto para despliegue
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Descargar el artefacto del trabajo de construcción
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-app

      # Verificar el archivo descargado
      - name: Verify Downloaded Artifact
        run: ls

      # Desplegar en Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'api-test-eb'
          environment_name: 'api-test-eb-env'
          region: us-east-1
          version_label: v-${{ github.run_id }}
          deployment_package: *.jar # Usar el artefacto descargado
