name: CI/CD Pipeline with Spring Boot, Gradle, and Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Java
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Dar permisos de ejecución al wrapper de Gradle
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      # Construir el proyecto
      - name: Build with Gradle
        run: ./gradlew clean build

      # Verificar el archivo JAR generado
      - name: Verify JAR file
        run: ls build/libs/

      # Iniciar el servidor Spring Boot para pruebas locales
      - name: Start Spring Boot Server
        run: |
          nohup java -jar build/libs/*.jar & # Usar el JAR generado
        env:
          SPRING_PROFILES_ACTIVE: test



      # Desplegar en Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: javaspring-back # Cambia esto por el nombre de tu aplicación
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_id }}
          deployment_package: build/libs/api-test-1.0.0.jar # Archivo que será desplegado
