name: CI/CD Pipeline with Spring Boot, Gradle, and Newman

on:
  push:
    branches:
      - main  # O la rama que prefieras
  pull_request:
    branches:
      - main  # O la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código fuente del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Java y Gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      # Paso 3: Instalar Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Paso 4: Construir el proyecto con Gradle (sin ejecutar las pruebas por ahora)
      - name: Build with Gradle
        run: ./gradlew build -x test  # Compila el proyecto, pero omite las pruebas por ahora

      # Paso 5: Instalar Node.js y Newman
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      # Paso 6: Ejecutar la colección de Postman con Newman
      - name: Run Postman Collection with Newman
        run: newman run ./collections/games.postman_collection.json --reporters cli,html --reporter-html-export ./newman-report.html

      # Paso 7: Subir el reporte HTML como un artifact
      - name: Upload Newman Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: ./newman-report.html
